### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kaplun** [inspirehep/invenio-workflows#7]
Visiting: https://labs.inspirehep.net/admin/holdingpen/details/54462

raises an unhandled exception: 
```python
Traceback (most recent call last):
  File "/opt/inspire/src/invenio/invenio/ext/legacy/__init__.py", line 119, in __call__
    response = self.app.full_dispatch_request()
  File "/opt/inspire/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/inspire/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/opt/inspire/src/invenio/invenio/base/wrappers.py", line 133, in handle_user_exception
    return super(Flask, self).handle_user_exception(e)
  File "/opt/inspire/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/inspire/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/inspire/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/inspire/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/opt/inspire/lib/python2.7/site-packages/flask_principal.py", line 199, in _decorated
    rv = f(*args, **kw)
  File "/opt/inspire/src/invenio/invenio/modules/workflows/views/holdingpen.py", line 224, in details
    formatted_data = bwobject.get_formatted_data()
  File "/opt/inspire/src/invenio/invenio/modules/workflows/models.py", line 431, in get_formatted_data
    of=of
  File "/opt/inspire/src/inspire/inspire/modules/deposit/workflows/literature.py", line 278, in formatter
    xml_record=marcxml
  File "/opt/inspire/src/invenio/invenio/modules/formatter/__init__.py", line 85, in format_record
    **kwargs)
  File "/opt/inspire/src/invenio/invenio/modules/formatter/engine.py", line 495, in format_record_1st_pass
    **kwargs)
  File "/opt/inspire/src/invenio/invenio/modules/formatter/engine.py", line 332, in format_record
    bfo = BibFormatObject(recID, ln, search_pattern, xml_record, user_info, of)
  File "/opt/inspire/src/invenio/invenio/modules/formatter/engine.py", line 1705, in __init__
    recID = record_get_field_value(self.record, "001") or None
  File "/opt/inspire/src/invenio/invenio/legacy/bibrecord/__init__.py", line 1042, in record_get_field_value
    if tag in rec:
TypeError: argument of type 'NoneType' is not iterable
```

Looks like the record is not allocated. I know this is old code, but it is just to ensure this does not happen on new one :-)

**Comment by jalavik** [comment]
No longer relevant on Invenio 3
